apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-plugin
spec:
  selector:
    matchLabels:
      name: example-plugin
  template:
    metadata:
      labels:
        name: example-plugin
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: example-plugin
        image: "example-plugin:v1"
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
